### ISSUE TITLE
About launch/diagnostic_msgs  question

### ISSUE THREAD

**Issue by alexleel** [homalozoa/ros2_for_beginners_code#6]
您好 关于这本书，有几个问题，期盼回复
1.请问可以通过配置launch 来控制ros2 节点的启停吗？
如果停止无法控制，那么在ros2里有没有类似的方法可以实现对节点的执行管理？
2. diagnostic 的功能只是通过收集硬件的msg来做一个整理汇总，具体行为还得自己去实现。我的理解对吗？
3. ros2 提供了很多时钟的基类。我们如何选择呢？
4. 在开发过程中，debug您经常用的是哪些？ gdb 还是trace ?

**Comment by homalozoa** [comment]
@alexleel 您好！很高兴收到您的提问。以下是一些我认为的答案，希望有所帮助。

> 1.请问可以通过配置launch 来控制ros2 节点的启停吗？

我不确定理解的是否正确，您的意思是否是在运行/执行launch.py之后，在命令行界面对节点的启动和停止进行操作？如果是这样的话，那么是可以实现的，但不推荐这种方式，因为命令行界面本身会输出很多日志，滚动的日志会冲掉您的操作记录。更好的办法是通过LifecycleNode的一些操作，比如通过Service进行状态的切换。

如果我理解的不正确，请更详细地描述这个问题，以便我提供回答。

> 2. diagnostic 的功能只是通过收集硬件的msg来做一个整理汇总，具体行为还得自己去实现。我的理解对吗？

是这样的。如何处理和分析这些数据，还需要用户自己来实现。

> 3. ros2 提供了很多时钟的基类。我们如何选择呢？

您指的是rclcpp::TimerBase派生的类吗，能否详细描述一下问题？

> 4. 在开发过程中，debug您经常用的是哪些？ gdb 还是trace ?

根据需求来，我也没有特别固守某一种调试工具，哪个最适合调试当前的问题就用哪个。比如说打断点还是使用GDB居多，调试性能可能会用到valgrind、memcheck等工具。

**Comment by alexleel** [comment]
您好 谢谢耐心回复，我对自己的疑惑详细说明一下：
> 我不确定理解的是否正确，您的意思是否是在运行/执行launch.py之后，在命令行界面对节点的启动和停止进行操作？如果是这样的话，那么是可以实现的，但不推荐这种方式，因为命令行界面本身会输出很多日志，滚动的日志会冲掉您的操作记录。更好的办法是通过LifecycleNode的一些操作，比如通过Service进行状态的切换。
就是对比Autosar 的EM（执行管理模块）：“当机器启动之后，OS会初始化EM作为初始进程，EM再加载其他的功能组，当平台基础组件运行起来之后，EM再根据Machine Manifest和Execution Manifest来按顺序启动平台应用和普通应用，EM负责按顺序启动和停止部署的应用” 
如果对比autosar，我的理解ros2中的launch 只能负责节点的拉起，节点如何停止，什么时候停止，需要 LifecycleNode management的一些操作来实现？

> 您指的是rclcpp::TimerBase派生的类吗，能否详细描述一下问题？
我的具体问题还是 Time Synchronization 相关的，书中解释是ros2有一些工具（realtime_tools and message-filters ）可以用来时钟同步，并且推荐 std::chrono库，那么 rclcpp::Clock 和rclcpp::TimerBase 我们什么时候用呢？

> 根据需求来，我也没有特别固守某一种调试工具，哪个最适合调试当前的问题就用哪个。比如说打断点还是使用GDB居多，调试性能可能会用到valgrind、memcheck等工具。
就是ros2本身的调试工具，比如ros2bag ros2trace 您用的并不多？

另外Lifecycle 生命周期管理，ros2并没有相关的实现，不知道,CyberDog或者nav2里是否有通用的实现方法呢？还是比对autosar的State Management(状态管理)， 他处理传入事件、确定这些事件/请求的优先级以设置相应的内部状态。

**Comment by alexleel** [comment]
另外 关于书中节点的单线程执行器，还有一个疑问：
书中说：“单线程节点执行器 表示管理的回调函数只会占用一个线程资源，并且会根据其指定的规则对回调顺序和优先级进行调度。多线程节点执行器表示其负责管理的回调函数可以占用多个线程” 请问优先级是在哪里设置呢，有更详尽的说明吗？
MultiThreadedExecutor 我在各个demo里看好像用的很少，但是我理解在多核处理器的机器上，肯定是多线程比较有性能优势，能简单说一下这几个ThreadedExecutor 的具体应用场景吗？

**Comment by homalozoa** [comment]
@alexleel 您好，我想我了解了您的疑问。

> 就是对比Autosar 的EM（执行管理模块）：“当机器启动之后，OS会初始化EM作为初始进程，EM再加载其他的功能组，当平台基础组件运行起来之后，EM再根据Machine Manifest和Execution Manifest来按顺序启动平台应用和普通应用，EM负责按顺序启动和停止部署的应用”
我的理解ros2中的launch 只能负责节点的拉起，节点如何停止，什么时候停止，需要 LifecycleNode management的一些操作来自己实现，ros2 launch本身是基于python 来执行，我能不能写好让节点何时起，何时停呢？

实际上ME和Launch所充当的角色很相似，都是负责启动和停止其他进程。在ROS 2的Launch设计中，也是用到了Python的多进程管理的功能。针对于`EM再根据Machine Manifest和Execution Manifest来按顺序启动平台应用和普通应用，EM负责按顺序启动和停止部署的应用`的设计，实际上我们在2021年设计cyberdog的时候已经有过相关考虑，可以参考一下[cyberdog_ros2/cyberdog_bringup](https://github.com/MiRoboticsLab/cyberdog_ros2/tree/main/cyberdog_bringup)的README了解一下，我们当时将应用分为了`base_nodes`和`other_nodes`，用于区分是机器启动所必需的应用程序和非必需的应用程序。当必需的应用程序无法被正常启动时，则BringUp流程会终止，非必需应用程序的启动失败不会影响到BringUp流程，只会报错。除此之外，我们还支持通过YAML配置不同的启动组，以快速切换应用程序组合。

其实ROS 2中的Launch程序从XML被修改为Python脚本后，提供了很多便利性，使之不再局限于XML的固定配置，而可以集成更多的操作。您可以尝试使用Python对一些功能进行设计和实现，以达到不同效果。有关何时启动和何时关闭的功能，也可以通过Python的功能和Launch的API进行实现，这些都是可以实现的，并且不需要LifecycleNode的协助。

此外，在Launch中操作LifecycleNode也是可以的，你可以直接通过API操作，比如使用`autostart`参数令其自启动，或者通过这里的一些event来操作，[launch_ros/launch_ros/events/lifecycle](https://github.com/ros2/launch_ros/tree/humble/launch_ros/launch_ros/events/lifecycle)。当然，如果觉得功能还不够多，也可通过在`launch_ros`中添加自己希望有的功能来增强该框架的丰富度。

> 具体问题还是 Time Synchronization 相关的，书中解释是ros2有一些工具（realtime_tools and message-filters ）可以用来时钟同步，并且推荐 std::chrono库，那么 rclcpp::Clock 和rclcpp::TimerBase 我们什么场景用呢？

rclcpp::Clock和rclcpp::TimerBase是两个不同功能的类，二者只有名字相似而已。前者是ROS 2中重要的时钟实现，它用来获取当前的系统时间、ROS虚拟时间或者基于时间进行一些操作，比如说delay和wait等。后者是ROS 2中用于操作某些功能运行的计时器类，它可以根据需求配置定时的操作，比如定时发布数据、定时更新参数等。

rclcpp::Clock实际上就是基于std::chrono进行实现的，可以参考[clock.hpp](https://github.com/ros2/rclcpp/blob/rolling/rclcpp/src/rclcpp/clock.cpp#L151)进行更深一步的了解。

> 另外Lifecycle 生命周期管理，ros2并没有相关的实现，不知道,CyberDog或者nav2里是否有通用的实现方法呢？还是比对autosar的State Management(状态管理)， 他处理传入事件、确定这些事件/请求的优先级以设置相应的内部状态。

LifecycleNode的周期管理实际上是应该用户自己来把握的，ROS 2的框架中仅仅给出了一些操作手段，比如通过Service或Message等，也可以通过内部的API进行直接操作。具体应用在ros2_controls、navigation2和cyberdog_ros2中都有体现。

> 书中说：“单线程节点执行器 表示管理的回调函数只会占用一个线程资源，并且会根据其指定的规则对回调顺序和优先级进行调度。多线程节点执行器表示其负责管理的回调函数可以占用多个线程” 请问优先级是在哪里设置呢，有更详尽的说明吗？
MultiThreadedExecutor 我在各个demo里看好像用的很少，但是我理解在多核处理器的机器上，肯定是多线程比较有性能优势，能简单说一下这几个ThreadedExecutor 的具体应用场景吗？

MultiThreadedExecutor用的少是故意的，因为具体到Single和Multi的区别，其实就是要看应用程序中是否包含需要用到多线程。比如如果进程中的节点需要使用到可重入（reentrant）的功能，那么必需使用MultiThreadedExecutor，否则可能会被其他线程卡死或卡死其他线程。如果一个应用程序中只包含一些基本的功能，放在一个线程跑即可，不会触发并发，则只需要使用SingleThreaded的执行器。

有关于调度优先级问题，在rclcpp中，想通过自定义去设置优先级需要修改executor，也就是自定义executor，默认的这几个executor都不支持自定义设置优先级。它们的调度方法是根据FIFO和回调函数处理时间动态调整的，具体可以参考[About Executors](https://docs.ros.org/en/humble/Concepts/About-Executors.html)了解。如果想尝试自定义调度逻辑的设置，可以参看rclc中的设计，或者直接配置waitset。waitset是executor调度的底层实现，直接通过它可以定义不同回调的优先级：[wait set examples](https://github.com/ros2/examples/tree/humble/rclcpp/wait_set)。

**Comment by alexleel** [comment]
@homalozoa 好的，谢谢您，十分清楚详尽。
还有一个关于topic的问题。  我在apex的paper里看到topic 区分为 non-triggering topics 和triggering topics:
https://www.apex.ai/post/a-journey-from-microcontrollers-to-microprocessors-with-autosar-ros
具体到代码 如何看topic 是否被激活或者被触发呢？

**Comment by homalozoa** [comment]
> @homalozoa 好的，谢谢您，十分清楚详尽。
> 
> 还有一个关于topic的问题。  我在apex的paper里看到topic 区分为 non-triggering topics 和triggering topics:
> 
> https://www.apex.ai/post/a-journey-from-microcontrollers-to-microprocessors-with-autosar-ros
> 
> 具体到代码 如何看topic 是否被激活或者被触发呢？

- 不用客气，很高兴能和您这样专注细心的读者交流！这个帖子我看了，他们在考虑的事情是多源数据融合时遇到的效率问题。这篇文章里所谓的triggering和non triggering指的其实是在topic订阅过程中，是否希望每次有topic消息事件发生时，都触发一次在定义subscription时所绑定（bind）的回调函数（callback）。如果每次都触发则是triggering，如果不想每次触发则是non triggering。因为如果考虑到多源头的传感器数据，其实是希望完全接收到一个时间段之内的所有传感器数据（topic）之后统一做融合处理，而不是每个独立的传感器数据（topic）数据到来后都触发一次回调（这会无意义地消耗CPU资源，也会影响整体实时性能）。所以他们对此做了一些优化，使得最后数据到齐后再做一次完整的回调融合处理。以上是我刚刚阅读那篇文章所理解的内容，希望有所帮助！

**Comment by alexleel** [comment]
> * 不想每次触发则是non triggering。因为如果考虑到多源头的传感器数据，其实是希望完全接收到一个时间段之内的所有传感器数据（topic）之后统一做融合处理，而不是每个独立的传感器数据（topic）数据到来后都触发一次回调（这会无意义地消耗CPU资源，也会影响整体实时性能）。所以他们对此做了一些优化，使得最后数据到齐后再做一次完整的回调融合处理。以上是我刚刚阅读那篇文章所理解的内容，希望有所帮助！
好的！ 谢谢！和您的沟通受益匪浅，期望您的新书：）

**Comment by alexleel** [comment]
> @alexleel 您好，我想我了解了您的疑问。
> 
> > 就是对比Autosar 的EM（执行管理模块）：“当机器启动之后，OS会初始化EM作为初始进程，EM再加载其他的功能组，当平台基础组件运行起来之后，EM再根据Machine Manifest和Execution Manifest来按顺序启动平台应用和普通应用，EM负责按顺序启动和停止部署的应用”
> > 我的理解ros2中的launch 只能负责节点的拉起，节点如何停止，什么时候停止，需要 LifecycleNode management的一些操作来自己实现，ros2 launch本身是基于python 来执行，我能不能写好让节点何时起，何时停呢？
> 
> 实际上ME和Launch所充当的角色很相似，都是负责启动和停止其他进程。在ROS 2的Launch设计中，也是用到了Python的多进程管理的功能。针对于`EM再根据Machine Manifest和Execution Manifest来按顺序启动平台应用和普通应用，EM负责按顺序启动和停止部署的应用`的设计，实际上我们在2021年设计cyberdog的时候已经有过相关考虑，可以参考一下[cyberdog_ros2/cyberdog_bringup](https://github.com/MiRoboticsLab/cyberdog_ros2/tree/main/cyberdog_bringup)的README了解一下，我们当时将应用分为了`base_nodes`和`other_nodes`，用于区分是机器启动所必需的应用程序和非必需的应用程序。当必需的应用程序无法被正常启动时，则BringUp流程会终止，非必需应用程序的启动失败不会影响到BringUp流程，只会报错。除此之外，我们还支持通过YAML配置不同的启动组，以快速切换应用程序组合。
> 
@homalozoa  有关cyberdog的实现细节，还有些问题想要咨询您，我在zhihu上发起了咨询，麻烦您有空可以check下
